vladalek/apps/account/urls.py
from django.urls import path
from .views import user_login, user_logout, user_about

app_name = "account"
urlpatterns = [
	path('', user_about, name='about'),
	path('login/', user_login, name="login"),
	path('logout/', user_logout, name="logout"),
]

vladalek/apps/blog/urls.py
from django.urls import path
from .views import index, detail, coments_list

app_name = 'blog'
urlpatterns = [
	path('', index, name='index'),
	path('<int:article_id>/', detail, name='detail'),
	path('<int:article_id>/coments_list/', coments_list, name='coments_list'),
]

vladalek/apps/home/urls.py
from django.urls import path
from .views import index, sitemap

app_name = 'home'
urlpatterns = [
	path('', index, name='index'),
	path("sitemap/", sitemap, name="sitemap"),
]

vladalek/apps/jarvis/urls.py
from django.urls import path
from .views import API

app_name = 'jarvis'
urlpatterns = [
	path('', API.as_view(), name='api'),
]

vladalek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
		path('grappelli/', include('grappelli.urls')),
		path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('jarvis/', include('jarvis.urls')),
]

handler404 = "vladalek.views.page_not_found_view"

vladalek/apps/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Profile(AbstractUser):
	code = models.TextField(blank=True, null=True, verbose_name='Код')
	avatar = models.URLField(blank=True, null=True, verbose_name="Аватар")
	email = models.EmailField(verbose_name='Почта')

vladalek/apps/blog/models.py
from django.db import models
from tinymce.models import HTMLField
from account.models import Profile

class Categories(models.Model):
	category = models.CharField(max_length=100,  verbose_name='Категорія')
	icon = models.CharField(max_length=100, verbose_name="Іконка")
	def __str__ (self):
		return self.category
	class Meta:
		verbose_name = "Категорія"
		verbose_name_plural = "Категорії"

class Articles(models.Model):
	categories = models.ForeignKey(Categories, null=True, related_name = "articles", on_delete = models.SET_NULL, verbose_name='Категорія')
	article_author = models.ForeignKey(Profile, related_name = "articles", on_delete = models.CASCADE, verbose_name='Автор статті')
	article_title = models.CharField(max_length=500, verbose_name='Назва статті')
	article_text = HTMLField(verbose_name='Текст статті')
	article_about = models.CharField(max_length=500, verbose_name='Опис статті')
	pub_date = models.DateField(auto_now_add=True)
	favorites = models.ManyToManyField(Profile, related_name="favourites", blank=True, verbose_name = "Обране")
	def __str__(self):
		return self.article_title
	class Meta:
		verbose_name = 'Стаття'
		verbose_name_plural = 'Статті'

class Coments(models.Model):
	articles = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='coments', verbose_name='До якої статті?')
	coment_author = models.ForeignKey(Profile, related_name = "coments", on_delete = models.CASCADE, verbose_name='Автор коментаря')
	coment_text = models.CharField(max_length=10000, verbose_name='Текст коментаря')
	pub_date = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.coment_text
	class Meta:
		verbose_name = 'Коментар'
		verbose_name_plural = 'Коментарі'

vladalek/apps/home/models.py
from django.db import models

vladalek/apps/jarvis/models.py
from django.db import models

# Create your models here.

vladalek/apps/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	
class RegisterForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)
	email = forms.CharField(widget=forms.EmailInput)

class CustomUserCreationForm(UserCreationForm):
	class Meta(UserCreationForm):
		model = Profile
		fields = ('username',)

class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = Profile
		fields = ('username',)

class ResetForm(forms.Form):
	username = forms.CharField()

class ResetConfirmForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)

class AvatarForm(forms.Form):
	avatar = forms.CharField()
	
class DeleteForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput)

vladalek/apps/blog/forms.py
from django import forms

class ComentForm(forms.Form):
	text = forms.CharField()

class CreateArticleForm(forms.Form):
	categories = forms.CharField()
	article_title = forms.CharField(max_length=20)
	text_article = forms.CharField()
	article_about = forms.CharField(max_length=100)

class CreateCategoryForm(forms.Form):
	category = forms.CharField()

class EditArticleForm(forms.Form):
	article_title = forms.CharField(max_length=20)
	text_article = forms.CharField()
	article_about = forms.CharField(max_length=100)

vladalek/apps/account/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import login, logout
from .models import Profile
from .forms import AvatarForm

def user_login(request):
	return render(request, 'account/login.html')

def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home:index'))

def user_about(request):
	if request.user.is_authenticated:
		user = Profile.objects.get(username = request.user.username)
		bookmark = user.favourites.all()
		if request.method=="POST" and "change_photo" in request.POST:
			form = AvatarForm(request.POST)
			if form.is_valid():
				cd = form.cleaned_data
				avatar = cd['avatar']
				user.avatar = avatar
				user.save()
		context = {'user': user, "bookmark": bookmark}
	else:
		return HttpResponseRedirect(reverse('account:login'))
	return render(request, 'account/about.html', context)

vladalek/apps/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Articles, Coments, Categories
from .forms import ComentForm
from account.models import Profile

def index(request):
	categories = request.GET.get('category', '')
	categories_list = Categories.objects.all()
	if categories:
		try:
			cat = Categories.objects.get(category=categories)
			articles_list = cat.articles.order_by('-id')
			return render(request, "blog/index.html", {"articles_list": articles_list})
		except:
			return render(request, "404.html")
	else:
		return render(request, "blog/categories.html", {"categories": categories_list})

def detail(request, article_id):
	try:
		a = Articles.objects.get(id = article_id)
	except:
		return render(request, "404.html")
	coments_list = a.coments.order_by('id')[:8]
	if request.method=="POST" and "add_coment" in request.POST:
		form = ComentForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			text = cd['text']
			Coments.objects.create(articles=a ,coment_text=text, coment_author=Profile.objects.get(username=request.user.username))
			return HttpResponseRedirect(reverse('blog:detail', args=(a.id,)))
	elif request.method=="POST" and "add_favourite" in request.POST:
		if request.user.is_authenticated:
			if request.user in a.favorites.all():
				a.favorites.remove(request.user)
			else:
				a.favorites.add(request.user)
		else:
			return HttpResponseRedirect(reverse('account:login'))
	if request.user in a.favorites.all():
		fav = True
	else:
		fav = False
	context = {'a': a, 'coments_list': coments_list, "fav": fav}
	
	return render(request, 'blog/detail.html', context,)

def coments_list(request, article_id):
	try:
		a = Articles.objects.get(id = article_id)
	except:
		return render(request, "404.html")
	coments_list = a.coments.all()
	paginator = Paginator(coments_list, 20)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	page = paginator.get_page(page_num)
	context = {"page": page, "coments_list": page.object_list, "a": a}
	
	return render(request, "blog/coments_list.html", context,)

vladalek/apps/home/views.py
from django.shortcuts import render
from blog.models import Articles
from account.models import Profile

def index(request):
	return render(request, 'home/index.html',)

def sitemap(request):
	
	return render(request, 'sitemap/sitemap.xml')

vladalek/apps/jarvis/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseRedirect
from django.views import View
from django.urls import reverse
import json, os
from .dialog import get_generative_replica

@method_decorator(csrf_exempt, name='dispatch')
class API(View):
	def get(self, request):
		return render(request, 'jarvis/index.html')
	
	def post(self, request):
		text, name="ERROR!","Metimol"
		post_body = json.loads(request.body)
		password = post_body.get("password")
		if password==os.environ["password_jarvis"]:
			text = post_body.get("text")
			answer = get_generative_replica(text)
		data = {
			'name': name,
			'text': answer,
		}
		return JsonResponse(data)

vladalek/views.py
from django.shortcuts import render

def page_not_found_view(request, exception):
	return render(request, '404.html', status=404)

vladalek/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="uk">
	<head>
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-RRSHD1PGBH"></script>
		<script>
  		window.dataLayer = window.dataLayer || [];
  		function gtag(){dataLayer.push(arguments);}
  		gtag('js', new Date());

  		gtag('config', 'G-RRSHD1PGBH');
		</script>
		<meta charset="utf-8">
		<meta name="google-site-verification" content="BeiVEBJ7dxeDHBb4Q_qq2hIXIrY2VBFthobaT8msT_c" />
		<title>{% block title %}Vladalek{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Блог програмісту на реальних прикладах." />
		<meta name="keywords" content="програмування на python, програмування на пайтон, програмування, блог, блог програміста, vladalek, metimol, python, пайтон, frontent, backend" />
		<meta name="author" content="metimol" />
		<link rel="stylesheet" href="{% static 'css/base.css' %}">
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/favicon/apple-touch-icon.png' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon/favicon-32x32.png' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon/favicon-16x16.png' %}">
		<link rel="shortcut icon" href="{% static 'media/favicon/favicon.ico' %}">
		<link rel="manifest" href="{% static 'media/favicon/site.webmanifest' %}">
		<link href="https://use.fontawesome.com/releases/v6.3.0/css/all.css" rel="stylesheet">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=ZCOOL+KuaiLe&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Fruktur&family=Source+Sans+Pro&display=swap" rel="stylesheet">
  	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
		{% block script %}{% endblock %}
	</head>

	{% block body %}<body>{% endblock %}
		<header>
			<div class="logo">
				<a href="{% url 'home:index' %}">VLADALEK</a>
			</div>
		</header>
		<div class='content'>
			{% block content %}{% endblock %}

		</div>
<nav class="navbar">
  <ul class="navbar-list">
    <li class="navbar-item">
      <a class="navbar-link" href="{% url 'home:index' %}">
        <i class="bi bi-house navbar-link-icon"></i>
      </a>
    </li>

    <li class="navbar-item">
      <a class="navbar-link" href="{% url 'blog:index' %}">
        <i class="bi bi-chat-quote navbar-link-icon"></i>
      </a>
    </li>

    <li class="navbar-item">
      <a class="navbar-link" href="{% url 'jarvis:api' %}">
        <i class="bi bi-robot navbar-link-icon"></i>
      </a>
    </li>

    <li class="navbar-item">
      <a class="navbar-link" href="{% url 'account:about' %}">
        <i class="bi bi-person navbar-link-icon"></i>
      </a>
    </li>
  </ul>
</nav>
<div class="preloader" id="preloader">
	<div class="loader">
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
 	 <div class="bar"></div>
	</div>
	<div class="circle"></div>
</div>

		<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
		<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
		{% block js %}{% endblock %}
		{% block loader_js %}
		<script>
			window.onload = function() {
				var preloader = document.getElementById('preloader');
				preloader.style.display = "none";
			}
		</script>
		{% endblock %}
	</body>
</html>