vladalek/apps/account/urls.py
from django.urls import path
from .views import user_login, user_logout, user_about

app_name = "account"
urlpatterns = [
	path('', user_about, name='about'),
	path('login/', user_login, name="login"),
	path('logout/', user_logout, name="logout"),
]

vladalek/apps/blog/urls.py
from django.urls import path
from .views import index, detail, coments_list

app_name = 'blog'
urlpatterns = [
	path('', index, name='index'),
	path('<int:article_id>/', detail, name='detail'),
	path('<int:article_id>/coments_list/', coments_list, name='coments_list'),
]

vladalek/apps/home/urls.py
from django.urls import path
from .views import index, sitemap

app_name = 'home'
urlpatterns = [
	path('', index, name='index'),
	path("sitemap/", sitemap, name="sitemap"),
]

vladalek/apps/jarvis/urls.py
from django.urls import path
from .views import API

app_name = 'jarvis'
urlpatterns = [
	path('', API.as_view(), name='api'),
]

vladalek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
		path('grappelli/', include('grappelli.urls')),
		path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('jarvis/', include('jarvis.urls')),
]

handler404 = "vladalek.views.page_not_found_view"

vladalek/apps/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Profile(AbstractUser):
	code = models.TextField(blank=True, null=True, verbose_name='Код')
	avatar = models.URLField(blank=True, null=True, verbose_name="Аватар")
	email = models.EmailField(verbose_name='Почта')

vladalek/apps/blog/models.py
from django.db import models
from tinymce.models import HTMLField
from account.models import Profile

class Categories(models.Model):
	category = models.CharField(max_length=100,  verbose_name='Категорія')
	icon = models.CharField(max_length=100, verbose_name="Іконка")
	def __str__ (self):
		return self.category
	class Meta:
		verbose_name = "Категорія"
		verbose_name_plural = "Категорії"

class Articles(models.Model):
	categories = models.ForeignKey(Categories, null=True, related_name = "articles", on_delete = models.SET_NULL, verbose_name='Категорія')
	article_author = models.ForeignKey(Profile, related_name = "articles", on_delete = models.CASCADE, verbose_name='Автор статті')
	article_title = models.CharField(max_length=500, verbose_name='Назва статті')
	article_text = HTMLField(verbose_name='Текст статті')
	article_about = models.CharField(max_length=500, verbose_name='Опис статті')
	pub_date = models.DateField(auto_now_add=True)
	favorites = models.ManyToManyField(Profile, related_name="favourites", blank=True, verbose_name = "Обране")
	def __str__(self):
		return self.article_title
	class Meta:
		verbose_name = 'Стаття'
		verbose_name_plural = 'Статті'

class Coments(models.Model):
	articles = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='coments', verbose_name='До якої статті?')
	coment_author = models.ForeignKey(Profile, related_name = "coments", on_delete = models.CASCADE, verbose_name='Автор коментаря')
	coment_text = models.CharField(max_length=10000, verbose_name='Текст коментаря')
	pub_date = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.coment_text
	class Meta:
		verbose_name = 'Коментар'
		verbose_name_plural = 'Коментарі'

vladalek/apps/home/models.py
from django.db import models

vladalek/apps/jarvis/models.py
from django.db import models

# Create your models here.

vladalek/apps/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	
class RegisterForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)
	email = forms.CharField(widget=forms.EmailInput)

class CustomUserCreationForm(UserCreationForm):
	class Meta(UserCreationForm):
		model = Profile
		fields = ('username',)

class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = Profile
		fields = ('username',)

class ResetForm(forms.Form):
	username = forms.CharField()

class ResetConfirmForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)

class AvatarForm(forms.Form):
	avatar = forms.CharField()
	
class DeleteForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput)

vladalek/apps/blog/forms.py
from django import forms

class ComentForm(forms.Form):
	text = forms.CharField()

class CreateArticleForm(forms.Form):
	categories = forms.CharField()
	article_title = forms.CharField(max_length=20)
	text_article = forms.CharField()
	article_about = forms.CharField(max_length=100)

class CreateCategoryForm(forms.Form):
	category = forms.CharField()

class EditArticleForm(forms.Form):
	article_title = forms.CharField(max_length=20)
	text_article = forms.CharField()
	article_about = forms.CharField(max_length=100)

vladalek/apps/account/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import login, logout
from .models import Profile
from .forms import AvatarForm

def user_login(request):
	return render(request, 'account/login.html')

def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home:index'))

def user_about(request):
	if request.user.is_authenticated:
		user = Profile.objects.get(username = request.user.username)
		bookmark = user.favourites.all()
		if request.method=="POST" and "change_photo" in request.POST:
			form = AvatarForm(request.POST)
			if form.is_valid():
				cd = form.cleaned_data
				avatar = cd['avatar']
				user.avatar = avatar
				user.save()
		context = {'user': user, "bookmark": bookmark}
	else:
		return HttpResponseRedirect(reverse('account:login'))
	return render(request, 'account/about.html', context)

vladalek/apps/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Articles, Coments, Categories
from .forms import ComentForm
from account.models import Profile

def index(request):
	categories = request.GET.get('category', '')
	categories_list = Categories.objects.all()
	if categories:
		try:
			cat = Categories.objects.get(category=categories)
			articles_list = cat.articles.order_by('-id')
			return render(request, "blog/index.html", {"articles_list": articles_list})
		except:
			return render(request, "404.html")
	else:
		return render(request, "blog/categories.html", {"categories": categories_list})

def detail(request, article_id):
	try:
		a = Articles.objects.get(id = article_id)
	except:
		return render(request, "404.html")
	coments_list = a.coments.order_by('id')[:8]
	if request.method=="POST" and "add_coment" in request.POST:
		form = ComentForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			text = cd['text']
			Coments.objects.create(articles=a ,coment_text=text, coment_author=Profile.objects.get(username=request.user.username))
			return HttpResponseRedirect(reverse('blog:detail', args=(a.id,)))
	elif request.method=="POST" and "add_favourite" in request.POST:
		if request.user.is_authenticated:
			if request.user in a.favorites.all():
				a.favorites.remove(request.user)
			else:
				a.favorites.add(request.user)
		else:
			return HttpResponseRedirect(reverse('account:login'))
	if request.user in a.favorites.all():
		fav = True
	else:
		fav = False
	context = {'a': a, 'coments_list': coments_list, "fav": fav}
	
	return render(request, 'blog/detail.html', context,)

def coments_list(request, article_id):
	try:
		a = Articles.objects.get(id = article_id)
	except:
		return render(request, "404.html")
	coments_list = a.coments.all()
	paginator = Paginator(coments_list, 20)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	page = paginator.get_page(page_num)
	context = {"page": page, "coments_list": page.object_list, "a": a}
	
	return render(request, "blog/coments_list.html", context,)

vladalek/apps/home/views.py
from django.shortcuts import render
from blog.models import Articles
from account.models import Profile

def index(request):
	return render(request, 'home/index.html',)

def sitemap(request):
	
	return render(request, 'sitemap/sitemap.xml')

vladalek/apps/jarvis/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseRedirect
from django.views import View
from django.urls import reverse
import json, os
from .dialog import get_generative_replica

@method_decorator(csrf_exempt, name='dispatch')
class API(View):
	def get(self, request):
		return render(request, 'jarvis/index.html')
	
	def post(self, request):
		text, name="ERROR!","Metimol"
		post_body = json.loads(request.body)
		password = post_body.get("password")
		if password==os.environ["password_jarvis"]:
			text = post_body.get("text")
			answer = get_generative_replica(text)
		data = {
			'name': name,
			'text': answer,
		}
		return JsonResponse(data)

vladalek/views.py
from django.shortcuts import render

def page_not_found_view(request, exception):
	return render(request, '404.html', status=404)

vladalek/templates/blog/categories.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/blog/categories.css' %}">
{% endblock %}

{% block content %}
<div class="wrap">
  <div class="flex-inner">
    <h2 class="p-title"><i class="fa-solid fa-feather-pointed"></i>Оберіть категорію:</h2>
    <div class="menu-list">
      <ul>
      	{% for i in categories %}
        <li onclick="window.location.href = '?category={{i.category}}'"><i class="{{ i.icon }}"></i>{{ i.category }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

vladalek/templates/blog/coments_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Коментарі{% endblock %}

{% block script %}
<link rel="stylesheet" href="{% static 'css/blog/detail.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<ion-icon name="chevron-back-outline" class="back" onclick="window.location='{% url "blog:detail" a.id %}';"></ion-icon>
<div class="coment_list">
	{% for i in coments_list %}
	{% if i.coment_author.username == user.get_username %}
	<div class="you_coment">
		<div class="author">
			<p>{{ i.coment_author.username }}</p>
		</div>
		<div class="coment_text">
			<p>{{ i.coment_text }}</p>
		</div>
		<div class="coment_date">
			{{ i.pub_date }}
		</div>
	</div>
	{% else %}
	<div class="coment">
		<div class="author">
			<p>{{ i.coment_author.username }}</p>
		</div>
		<div class="coment_text">
			<p>{{ i.coment_text }}</p>
		</div>
		<div class="coment_date">
			{{ i.pub_date }}
		</div>
	</div>
	{% endif %}
	{% endfor %}
</div>

{% endblock %}

vladalek/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<link rel="stylesheet" href="{% static 'css/blog/detail.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
{% endblock %}

{% block title %}{{a.article_title}}{% endblock %}

{% block content %}
	
	<div class="card">
		<div class="title">
			<h1>{{a.article_title}}</h1>
		</div>
		<div class="bookmark">
		<form method="POST" action="{% url  'blog:detail' a.id %}">
			{% csrf_token %}
			<button type="submit" name="add_favourite" id="bookmark">
			{% if fav %}
			<ion-icon name="bookmark"></ion-icon>
			{% else %}
			<ion-icon name="bookmark-outline"></ion-icon>
			{% endif %}
			</button>
		</form>
		</div>
		<div class="text_content">
			<div class="text">
				{{a.article_text | safe}}
				<script async src="https://zvwhrc.com/na/waWQiOjExNDkwMjgsInNpZCI6MTE4OTQ5MCwid2lkIjo0MzE3MzksInNyYyI6Mn0=eyJ.js"></script>
			</div>
			<div class="date">
				{{a.pub_date}}
			</div>
		</div>
		<div class="coments">
			<span>Коментарі:</span>
			{% if user.is_authenticated %}
			<div class="add_coment">
				<form action="{% url  'blog:detail' a.id %}" method="POST">
					{% csrf_token %}
					<div class="block">
						<input name="text" id="text" type="text" class="form-control" required autocomplete="off">
						<label>Ваш комментар</label>
					</div>
					<div class="next">
						<input type="submit" name="add_coment" value="Отправить" id="send" />
					</div>
				</form>
			</div>
			{% else %}
			<div class="non_auth">
				<a href="{% url 'account:login' %}">Увійдіть, щоб залишити коментар.</a>
			</div>
			{% endif %}
			{% for i in coments_list %}
			{% if i.coment_author.username == user.get_username %}
			<div class="you_coment">
				<div class="author">
					<p>{{ i.coment_author.username }}</p>
				</div>
				<div class="coment_text">
					<p>{{ i.coment_text }}</p>
				</div>
				<div class="coment_date">
					{{ i.pub_date }}
				</div>
			</div>
			{% else %}
			<div class="coment">
				<div class="author">
					<p>{{ i.coment_author.username }}</p>
				</div>
				<div class="coment_text">
					<p>{{ i.coment_text }}</p>
				</div>
				<div class="coment_date">
					{{ i.pub_date }}
				</div>
			</div>
			{% endif %}
			{% endfor %}
			{% if coments_list|length > 7 %}
			<div class="detail_coments">
				<a href="{% url 'blog:coments_list' a.id %}"><span>Читати всі коментарі</span></a>
			</div>
			{% endif %}
		</div>
	</div>

	{% endblock %}

	{% block js %}
	<script>hljs.highlightAll();</script>
	{% endblock %}

vladalek/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css'>
<link rel="stylesheet" href="{% static 'css/blog/index.css' %}">
{% endblock %}

{% block content %}

{% if articles_list %}
<div class="blog-slider">
  <div class="blog-slider__wrp swiper-wrapper">
    {% for a in articles_list %}
    <div class="blog-slider__item swiper-slide">
      <div class="blog-slider__img"> 
        <img src="https://res.cloudinary.com/muhammederdem/image/upload/q_60/v1535759872/kuldar-kalvik-799168-unsplash.webp" alt="">
      </div>
      <div class="blog-slider__pagination"></div>
      <div class="blog-slider__content">
        <span class="blog-slider__code">{{a.pub_date}}</span>
        <div class="blog-slider__title">{{a.article_title}}</div>
        <div class="blog-slider__text">{{a.article_about}}</div>
        <a href="{% url 'blog:detail' a.id %}" class="blog-slider__button">Читати далі</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<div class="no">Статей немає :(</div>
{% endif %}

{% endblock %}

{% block js %}

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js'></script>
<script src="{% static 'js/blog/index.js' %}"></script>

{% endblock %}